apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stern
  labels:
    wireService: stern
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      wireService: stern
  template:
    metadata:
      labels:
        wireService: stern
        release: {{ .Release.Name }}
      annotations:
        # An annotation of the configmap checksum ensures changes to the configmap cause a redeployment upon `helm upgrade`
        checksum/configmap: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      volumes:
        - name: "stern-config"
          configMap:
            name: "stern"
      containers:
        - name: stern
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
          volumeMounts:
          - name: "stern-config"
            mountPath: "/etc/wire/stern/conf"
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /i/status
              port: {{ .Values.service.internalPort }}
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /i/status
              port: {{ .Values.service.internalPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
