# CHANGEME-PROD: NodePort is more friendly to use than a dedicated LB such as metallb
#                when in layer-2 mode since it listens on all k8s nodes; this is a typical
#                setup when all your k8s nodes are on internal IPs and thus this requires
#                setting up your firewall and forward 443 to 31773, as well as 80 to 31772
nginx-ingress:
  defaultBackend:
    image:
      imagePullPolicy: IfNotFound
    # nodeSelector:
    #   kubernetes.io/hostname: <some-host>
  controller:
    image:
      imagePullPolicy: IfNotFound
    # nodeSelector:
    #   kubernetes.io/hostname: <some-host>
    service:
      type: NodePort
      nodePorts:
        # NOTE: This has to match the port forwarded from the firewall for SSL (443) and TCP (80)
        https: 31773
        http: 31772
