# The assethost will host assets other machines will download
# this will be passed post adding the assethost node in the playbook
# assethost_host: "{{ hostvars['assethost'].ansible_host }}:8080"
# When set to true; will set up all the repos below before continuing
# to bootstrap; such that no network access is needed
offline: true

# This is used nowhere inside kubespray, only inside this file
# and our own playbooks
ubuntu_repos: "http://{{ assethost_host }}/debs-{{ ansible_distribution_release }}/public"
ubuntu_repo_base_url: "{{ ubuntu_repos }}"
ubuntu_repo_gpgkey: "{{ ubuntu_repos }}/gpg"

docker_ubuntu_repo_base_url: "{{ ubuntu_repos }}"
docker_ubuntu_repo_gpgkey: "{{ ubuntu_repos }}/gpg"
# docker_ubuntu_repo_repokey: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"

binaries_url: "http://{{ assethost_host }}/binaries"

kubeconfig_localhost: true
#resolvconf_mode: none

# This defaults to true if http://169.254.169.254/latest/meta-data exists; which
# is also available in non-AWS. e.g. in Hetzner. Lets not let this autodetect in offline
is_aws_environment: False

# IP address for the logging (for example QRadar) server
syslog_target_ip: 12.34.56.78
