# CHANGEME-PROD: All values here should be changed/reviewed
brig:
  secrets:
    smtpPassword: dummyPassword
    zAuth:
      # generate zauth public/private keys with the 'zauth' executable from wire-server:
      # ./dist/zauth -m gen-keypair -i 1
      publicKeys: "<public key>"
      privateKeys: "<private key>"
    turn:
      # generate a high-entropy random string, e.g. using
      # openssl rand -base64 64 | env LC_CTYPE=C tr -dc a-zA-Z0-9 | head -c 42
      secret: CHANGEMEE6KHMJU1uDhhgvsVWoIyzmn3u3GHRoWjTp
    # these only need to be changed if using real AWS services
    awsKeyId: dummykey
    awsSecretKey: dummysecret
    # These are only necessary if you wish to support sign up via SMS/calls
    # And require accounts at twilio.com / nexmo.com
    setTwilio: |-
      sid: "dummy"
      token: "dummy"
    setNexmo: |-
      key: "dummy"
      secret: "dummy"
    # Uncomment for federation. Set values accordingly

    # rabbitmq:
    #   username: wire-server
    #   password: verysecurepassword

cargohold:
  secrets:
    # these only need to be changed if using real AWS services
    awsKeyId: dummykey
    awsSecretKey: dummysecret

galley:
  secrets:
    # these only need to be changed if using real AWS services
    awsKeyId: dummykey
    awsSecretKey: dummysecret
    # Uncomment for federation below. Set values accordingly
    # rabbitmq:
    #   username: wire-server
    #   password: verysecurepassword

gundeck:
  secrets:
    # these only need to be changed if using real AWS services
    awsKeyId: dummykey
    awsSecretKey: dummysecret

proxy:
  secrets:
    # If you desire proxying/previews for the following services,
    # set 'tags.proxy: true' in demo-values.yaml,
    # create accounts with them and fill in these values:
    proxy_config: |-
      secrets {
              youtube    = "..."
              googlemaps = "..."
              soundcloud = "..."
              giphy      = "..."
              spotify    = "Basic ..."
      }

nginz:
  secrets:
    zAuth:
      # needs to match brig.secrets.zAuth.publicKeys
      publicKeys: "<public key>"
    # only necessary in test environments (env="staging"). See charts/nginz/README.md
    basicAuth: "<username>:<htpasswd-hashed-password>"


# Uncomment for federation below. Set values accordingly
# background-worker:
#   secrets:
#     rabbitmq:
#       username: wire-server
#       password: verysecurepassword

# Uncomment for legalhold. Set values accordingly

# legalhold:
#   serviceToken: "supersecret"
#   # openssl req -x509 -newkey rsa:4096 -sha256 -keyout tls.key -out tls.crt -days
#   # 365 -subj '/CN={{ .Values.legalhold.host }}' Or provide your own signed by a
#   # proper CA
#   tlsKey: |
#     -----BEGIN PRIVATE KEY-----
#     -----END PRIVATE KEY-----
#
#   tlsCrt: |
#     -----BEGIN CERTIFICATE-----
#     -----END CERTIFICATE-----
