# CHANGEME-PROD: All values here should be changed/reviewed
brig:
  secrets:
    #retrieve postgresql password from Kubernetes Secret with "kubectl get secret wire-postgresql-external-secret -n default -o jsonpath='{.data.password}' | base64 -d"
    pgPassword: verysecurepassword

    smtpPassword: dummyPassword
    zAuth:
      # generate zauth public/private keys with the 'zauth' executable from wire-server:
      # ./dist/zauth -m gen-keypair -i 1
      publicKeys: "<public key>"
      privateKeys: "<private key>"
    turn:
      # generate a high-entropy random string, e.g. using
      # openssl rand -base64 64 | env LC_CTYPE=C tr -dc a-zA-Z0-9 | head -c 42
      secret: CHANGEMEE6KHMJU1uDhhgvsVWoIyzmn3u3GHRoWjTp
    # these only need to be changed if using real AWS services
    awsKeyId: dummykey
    awsSecretKey: dummysecret
    # These are only necessary if you wish to support sign up via SMS/calls
    # And require accounts at twilio.com / nexmo.com
    rabbitmq:
      username: guest
      password: guest

cannon:
  secrets:
    rabbitmq:
      username: guest
      password: guest

cargohold:
  secrets:
    # Change the awsKeyId and awsSecretKey with the IAM user credentials for cargohold
    # Get the secrets and key from the ansible/inventory/offline/group_vars/all/secrets.yml
    awsKeyId: dummykey # replace with minio_cargohold_access_key
    awsSecretKey: dummysecret # replace with minio_cargohold_secret_key
    rabbitmq:
      username: guest
      password: guest

galley:
  secrets:
    #retrieve postgresql password from Kubernetes Secret with "kubectl get secret wire-postgresql-external-secret -n default -o jsonpath='{.data.password}' | base64 -d"
    pgPassword: verysecurepassword
    # these only need to be changed if using real AWS services
    awsKeyId: dummykey
    awsSecretKey: dummysecret
    rabbitmq:
      username: guest
      password: guest
    mlsPrivateKeys:
      removal:
        ed25519: |
          -----BEGIN PRIVATE KEY-----
          -----END PRIVATE KEY-----
        ecdsa_secp256r1_sha256: |
          -----BEGIN PRIVATE KEY-----
          -----END PRIVATE KEY-----
        ecdsa_secp384r1_sha384: |
          -----BEGIN PRIVATE KEY-----
          -----END PRIVATE KEY-----
        ecdsa_secp521r1_sha512: |
          -----BEGIN PRIVATE KEY-----
          -----END PRIVATE KEY-----

gundeck:
  secrets:
    # these only need to be changed if using real AWS services
    awsKeyId: dummykey
    awsSecretKey: dummysecret
    rabbitmq:
      username: guest
      password: guest

proxy:
  secrets:
    # If you desire proxying/previews for the following services,
    # set 'tags.proxy: true' in demo-values.yaml,
    # create accounts with them and fill in these values:
    proxy_config: |-
      secrets {
              youtube    = "..."
              googlemaps = "..."
              soundcloud = "..."
              giphy      = "..."
              spotify    = "Basic ..."
      }

nginz:
  secrets:
    zAuth:
      # needs to match brig.secrets.zAuth.publicKeys
      publicKeys: "<public key>"
    # only necessary in test environments (env="staging"). See charts/nginz/README.md
    basicAuth: "<username>:<htpasswd-hashed-password>"


# RabbitMQ credentials for background-worker.
background-worker:
  secrets:
    rabbitmq:
      username: guest
      password: guest

# Uncomment for legalhold. Set values accordingly

# legalhold:
#   serviceToken: "supersecret"
#   # openssl req -x509 -newkey rsa:4096 -sha256 -keyout tls.key -out tls.crt -days
#   # 365 -subj '/CN={{ .Values.legalhold.host }}' Or provide your own signed by a
#   # proper CA
#   tlsKey: |
#     -----BEGIN PRIVATE KEY-----
#     -----END PRIVATE KEY-----
#
#   tlsCrt: |
#     -----BEGIN CERTIFICATE-----
#     -----END CERTIFICATE-----
