#
# You will need to define:
#  - cassandra_role_name (gundeck, brig, galley or spar)
#
- name: Run repair - wait for up to 2h, poll every 10 sec
  # This is copied from the crontab in cassandra/tasks/cron
  shell: "flock -n /tmp/backup_repair_mutex /usr/local/bin/cassandra_repair_{{ cassandra_role_name }} | svlogd -tt /var/log/cassandra_repair/"
  async: 7200
  poll: 10
