# Disable since prod should use an externally provided minio
enabled: false
minio:
  image:
    repository: quay.io/wire/mirror-images/minio/minio
    tag: RELEASE.2023-07-07T07-13-57Z
  mcImage:
    repository: quay.io/wire/mirror-images/minio/mc
    tag: RELEASE.2023-06-28T21-54-17Z
