# Required job to run after upgrading to wire-server-5.12.0 or newer
apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-features
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: migrate-features
          image: quay.io/wire/migrate-features:5.12.0
          args:
            [
              --cassandra-host-galley,
              "<galley-host>",
              --cassandra-port-galley,
              "9042",
              --cassandra-keyspace-galley,
              galley,
            ]
      restartPolicy: Never
  backoffLimit: 4