{
 "title": "Message Stats",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "kube_namespace_labels" }
  ]
 },
 "panels": [
  { "title": "Brig Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Registrations/invitations/code requests (brig)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{handler=\"/teams/:tid/invitations\", status_code=\"201\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "invitations/sec(201)"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{handler=\"/register\", status_code=\"201\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "registration/sec(201)"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{handler=\"/activate/send\", status_code=~\"200\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "code_requests/sec(200)"
    }
   ]
  },
  { "title": "Cannon Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Connected Clients (cannon)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(net_websocket_clients{namespace=\"$namespace\"})",
     "legendFormat": "Connected Clients"
    }
   ]
  },
  { "title": "Gundeck Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Message Push Latencies (gundeck)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{handler=\"/i/push/v2\", namespace=\"$namespace\"}[5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Native Push (Outgoing) (gundeck)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(push_native_success[5m]))",
     "legendFormat": "Success"
    },
    {
     "expr": "-sum(increase(push_native_disabled[5m]))",
     "legendFormat": "-Disabled"
    },
    {
     "expr": "-sum(increase(push_native_invalid{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "-Invalid"
    },
    {
     "expr": "-sum(increase(push_native_errors{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "-Errors"
    }
   ]
  },
  {
   "title": "Push Rate (incoming) (gundeck)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{role=\"gundeck\", handler=\"/i/push/v2\", namespace=\"$namespace\"}[5m])) by (status_code)",
     "legendFormat": "{{ status_code }}"
    }
   ]
  },
  {
   "title": "Push Status Codes as % (gundeck)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{handler=\"/i/push/v2\", namespace=\"$namespace\"}) by (status_code)",
     "legendFormat": "{{ status_code }}"
    }
   ]
  },
  { "title": "Galley Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Message POSTing Latencies (galley)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{handler=\"/conversations/:cnv/otr/messages\", namespace=\"$namespace\"}[5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "OTR Message Receives as % by Status Code (galley)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{role=\"galley\", handler=\"/conversations/:cnv/otr/messages\", status_code=~\"2..\", namespace=\"$namespace\"}[10m]))",
     "legendFormat": "2XX"
    },
    {
     "expr": "sum(increase(http_request_duration_seconds_count{role=\"galley\", handler=\"/conversations/:cnv/otr/messages\", status_code=~\"4..\", namespace=\"$namespace\"}[10m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(increase(http_request_duration_seconds_count{role=\"galley\", handler=\"/conversations/:cnv/otr/messages\", status_code=~\"5..\", namespace=\"$namespace\"}[10m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Messages Sent every 5m (galley)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{handler=\"/conversations/:cnv/otr/messages\", status_code=~\"2..\", namespace=\"$namespace\"}[5m]))"
    }
   ]
  }
 ]
}