# Only checks if a given cassandra cluster is healthy
#
- name: Check cluster is healthy
  hosts: cassandra
  any_errors_fatal: yes
  gather_facts: no
  tasks:
    - include: tasks/cassandra_cluster_healthy.yml
