secrets:
  zrestSecret: "secret"
# Assuming you run helm directly (and not helm-wrapper with sops), you can
# simply drop your certificate/private key here. Be careful with spaces/indentation,
# as the ingress seems to simply "swallow" errors if any (and serve the Fake default certificate
# which is highly confusing)
federate:
  dtls:
    tls:
      # If you are having trouble with YAML formatting (getting validation errors due to spacing/indentation)
      # try running helm with --set federate.dtls.tls.crt=your-cert.pem --set deferate.dtls.tls.key=your-key.pem
      # instead
      crt: |
        -----BEGIN CERTIFICATE-----
        .... OWN CERTIFICATE ......
        -----END CERTIFICATE-------
        -----BEGIN CERTIFICATE-----
        .... INTERMEDIATE CERT ....
        -----END CERTIFICATE-------
      key: |
        -----BEGIN PRIVATE KEY-----
        .... REAL PRIV KEY  .......
        -----END PRIVATE KEY-------
