replicaCount: 1
image:
  repository: quay.io/wire/stern
  tag: 2.53.3
  pullPolicy: IfNotPresent
config:
  logLevel: Info
resources:
  requests:
    memory: 128Mi
    cpu: 125m
  limits:
    memory: 512Mi
    cpu: 500m
service:
  internalPort: 8080
  externalPort: 8080
