---
# Handlers for RabbitMQ
- name: restart rabbitmq-server
  service: name=rabbitmq-server state=restarted

- name: start rabbitmq-server
  service: name=rabbitmq-server state=started

- name: stop rabbitmq-server
  service: name=rabbitmq-server state=stopped
