# CHANGEME-PROD: Assuming you run helm directly (and not helm-wrapper with sops), you can
# simply drop your certificate/private key here. Be careful with spaces/indentation,
# as the ingress seems to simply "swallow" errors if any (and serve the Fake default certificate
# which is highly confusing)
secrets:
  tlsClientCA: | # for federating backends root CA certificates
    -----BEGIN CERTIFICATE-----
    .... THEIR CERTIFICATE ....
    -----END CERTIFICATE-----
  tlsWildcardCert: |
    -----BEGIN CERTIFICATE-----
    .... OWN CERTIFICATE ......
    -----END CERTIFICATE-------
    -----BEGIN CERTIFICATE-----
    .... INTERMEDIATE CERT ....
    -----END CERTIFICATE-------
  tlsWildcardKey: |
    -----BEGIN PRIVATE KEY-----
    .... REAL PRIV KEY  .......
    -----END PRIVATE KEY-------
