teamSettings:
  enabled: true
accountPages:
  enabled: true
tls:
  enabled: true
  # NOTE: enable to automate certificate issuing with jetstack/cert-manager instead of
  #       providing your own certs in secrets.yaml. Cert-manager is not installed automatically,
  #       it needs to be installed beforehand (see ./../../charts/certificate-manager/README.md)
  useCertManager: false

certManager:
  inTestMode: false
  # CHANGEME-PROD: required, if certificate manager is used; set to receive cert expiration
  #                notice and other Letsencrypt related notification
  certmasterEmail:

# CHANGEME-PROD: These values are suggested for deployments on bare metal and
#                should be adjusted on a per installation basis
config:
  dns:
    https: nginz-https.default.domain
    ssl: nginz-ssl.default.domain
    webapp: webapp.default.domain
    fakeS3: assets.default.domain
    teamSettings: teams.default.domain
    accountPages: account.default.domain

service:
  s3:
    externalPort: 9000
    serviceName: minio-external
    externallyCreated: true
