# Default values for the webapp.
replicaCount: 1
resources:
  requests:
    memory: 256Mi
    cpu: "0.5"
  limits:
    memory: 512Mi
    cpu: "1"
image:
  repository: quay.io/wire/webapp
  tag: b17b78a626f0317e5259c10d973c9933e9205813
service:
  https:
    externalPort: 443
  http:
    webappPort: 8080

## The following has to be provided to deploy this chart

#config:
#  externalUrls:
#   backendRest: <nginz-subdomain-https.your.domain>
#   backendWebsocket: <nginz-subdomain-ssl.your.domain>
#   backendDomain: <your.domain>
#   webappHost: <nginz-subdomain-webapp.your.domain>
