# Default values for the webapp.
replicaCount: 1
resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "1"
image:
  repository: quay.io/wire/webapp
  tag: 44421-0.1.0-e438dc-v0.24.0-production
service:
  https:
    externalPort: 443
  http:
    internalPort: 8080

## The following has to be provided to deploy this chart

#config:
#  externalUrls:
#   backendRest: <nginz-subdomain-https.your.domain>
#   backendWebsocket: <nginz-subdomain-ssl.your.domain>
#   backendDomain: <your.domain>
#   appHost: <webapp-subdomain.your.domain>

# Some relevant environment options, have a look at
# https://github.com/wireapp/wire-webapp/wiki/Self-hosting
# NOTE: Without an empty dictionary, you will see warnings
#       when overriding envVars
envVars: {}
# E.g.
# envVars:
#   FEATURE_ENABLE_DEBUG: "true"
#
