replicaCount: 3
image:
  repository: quay.io/wire/gundeck
  tag: 2.90.0
service:
  externalPort: 8080
  internalPort: 8080
resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"
config:
  logLevel: Info
  cassandra:
    host: aws-cassandra
  redis:
    host: redis-ephemeral-master
    port: 6379
  bulkPush: false
  aws:
    region: "eu-west-1"
  proxy: {}
