replicaCount: 3
image:
  repository: quay.io/wire/gundeck
  tag: 2.58.0
service:
  externalPort: 8080
  internalPort: 8080
resources:
  requests:
    memory: 256Mi
    cpu: 250m
  limits:
    memory: 512Mi
    cpu: 500m
config:
  logLevel: Info
  cassandra:
    host: aws-cassandra
  redis:
    host: redis-ephemeral
    port: 6379
  bulkPush: false