{
 "title": "Calling / TURN / coturn",
 "tags": [
  "COTURN",
  "Calling"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  { "title": "coturn", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Allocations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(turn_total_allocations{namespace=\"$namespace\", service=\"coturn\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "(sum by (pod) (turn_total_allocations{namespace=\"$namespace\", service=\"coturn\"})) * on (pod) group_right kube_pod_info",
     "legendFormat": "{{pod}} / {{node}}"
    }
   ]
  },
  {
   "title": "Pod network traffic",
   "type": "timeseries",
   "description": "Network traffic usage reported by coturn. Note that per-session traffic usage is only reported after sessions have ended.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "-(sum by(pod) (rate(turn_total_traffic_sentb{namespace=\"$namespace\", service=\"coturn\"}[2m])) * on (pod) group_right kube_pod_info)",
     "legendFormat": "{{pod}} / {{node}} (sent)"
    },
    {
     "expr": "(sum by(pod) (rate(turn_total_traffic_rcvb{namespace=\"$namespace\", service=\"coturn\"}[2m]))) * on(pod) group_right kube_pod_info",
     "legendFormat": "{{pod}} / {{node}} (received)"
    }
   ]
  },
  {
   "title": "Pod network traffic (cumulative)",
   "type": "timeseries",
   "description": "Network traffic usage reported by coturn. Note that per-session traffic usage is only reported after sessions have ended.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(turn_total_traffic_sentb{namespace=\"$namespace\", service=\"coturn\"}[2m])) * -1",
     "legendFormat": "Bytes sent"
    },
    {
     "expr": "sum(rate(turn_total_traffic_rcvb{namespace=\"$namespace\", service=\"coturn\"}[2m]))",
     "legendFormat": "Bytes received"
    }
   ]
  },
  {
   "title": "Pod open file descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (pod) (process_open_fds{namespace=\"$namespace\",service=\"coturn\"}) * on (pod) group_right kube_pod_info",
     "legendFormat": "{{pod}} / {{node}}"
    },
    {
     "expr": "sum(process_open_fds{namespace=\"$namespace\", service=\"coturn\"})",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "coturn (host nodes)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "CPU total coturn nodes",
   "type": "timeseries",
   "description": "This calculates CPU usage (in cores) for Coturn pods, grouped by node.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (mode) (\n  sum by (instance, mode) (\n    rate(node_cpu_seconds_total{job=\"node-exporter\", mode!=\"idle\"}[2m])\n    * on (instance) group_left() (\n      label_replace(\n        kube_pod_info{namespace=\"default\", created_by_name=\"coturn\"},\n        \"instance\",\n        \"$1:9100\",\n        \"host_ip\",\n        \"(.*)\"\n      )\n    )\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network (coturn nodes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (node) (\n  rate(\n    container_network_transmit_bytes_total{\n      namespace=\"default\",\n      pod=~\"coturn.*\",\n      interface=\"eth0\"\n    }[2m]\n  )\n)",
     "legendFormat": "{{node}} (receive)"
    },
    {
     "expr": "-sum by (node) (\n  rate(\n    container_network_receive_bytes_total{\n      namespace=\"default\",\n      pod=~\"coturn.*\",\n      interface=\"eth0\"\n    }[2m]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network (coturn nodes, cumulative)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "\nsum (\n  rate(\n    container_network_transmit_bytes_total{\n      namespace=\"default\",\n      pod=~\"coturn.*\",\n      interface=\"eth0\"\n    }[2m]\n  )\n)",
     "legendFormat": "Total egress"
    },
    {
     "expr": "-sum (\n  rate(\n    container_network_receive_bytes_total{\n      namespace=\"default\",\n      pod=~\"coturn.*\",\n      interface=\"eth0\"\n    }[2m]\n  )\n)",
     "legendFormat": "Total ingress"
    }
   ]
  },
  {
   "title": "Load averages (coturn nodes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(node) (\n  label_replace(\n    node_load15,\n    \"internal_ip\", \"$1\", \"instance\", \"(.*):.*\"\n  )\n  * on (internal_ip) group_left(node)\n  kube_node_info\n  * on (node) group_left()\n  kube_pod_info{namespace=\"default\", created_by_name=\"coturn\"}\n)",
     "legendFormat": "{{node}} {{pod}} / 15min avg"
    },
    {
     "expr": "sum by(node) (\n  label_replace(\n    node_load5,\n    \"internal_ip\", \"$1\", \"instance\", \"(.*):.*\"\n  )\n  * on (internal_ip) group_left(node)\n  kube_node_info\n  * on (node) group_left()\n  kube_pod_info{namespace=\"default\", created_by_name=\"coturn\"}\n)",
     "legendFormat": "{{node}} {{pod}} / 5min avg"
    }
   ]
  }
 ]
}