{
 "title": "Cells One Pod - All info",
 "description": "Prepare monitoring in Wire Infra with different datasources (usually, Cells metrics + Node Exporter)",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Metrics DS", "query": "prometheus" },
   { "name": "logds", "label": "Log DS", "query": "loki" },
   {
    "name": "pod_id",
    "label": "Pod ID",
    "query": {
     "query": "label_values({pod=~\"cells-[0-9a-f]{10}-[0-9a-f].*\"},pod)"
    }
   },
   { "name": "instance", "label": "Process", "query": { "query": "label_values(instance)" } },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values({cluster=~\"grafana-agent.*\"},cluster)"
    }
   },
   {
    "name": "ns",
    "label": "Namespace",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 23, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cells_version_info{namespace=\"cells\"}",
     "legendFormat": "{{package_label}} {{version}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Cells Server log volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({namespace=~\"$ns\", pod=\"$pod_id\"} |= `` [5m]))",
     "legendFormat": "All msgs"
    },
    {
     "direction": "backward",
     "expr": "sum(count_over_time({namespace=~\"$ns\", pod=\"$pod_id\", type=\"syslog\"} |= `` [5m]))",
     "legendFormat": "All msgs"
    }
   ]
  },
  {
   "title": "Server errors",
   "type": "logs",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 3 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"$ns\", pod=\"$pod_id\"} |= `` | json | level=\"error\" | line_format \"{{.logger}}: {{.msg}}\""
    }
   ]
  },
  {
   "type": "logs",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 11 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"$ns\", pod=\"$pod_id\"} \n| json \n| __error__ = \"\" \n!~ \"panic|goroutine\" \n| line_format \"{{.logger}}: {{.msg}}\""
    }
   ]
  },
  {
   "title": "Panics",
   "type": "logs",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 22 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"$ns\", pod=\"$pod_id\"} |~ \"^(panic:|goroutine [0-9]+|\\\\s+\\\\S+\\\\.go:\\\\d+)\""
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Pod RAM",
   "type": "timeseries",
   "description": "## kind of broken:\nWe spin only one proces per instance by default in v5",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cells_process_runtime_go_mem_heap_alloc_bytes{pod=\"$pod_id\"}",
     "legendFormat": "Alloc Bytes"
    },
    {
     "expr": "cells_process_runtime_go_mem_heap_idle_bytes{pod=\"$pod_id\"}",
     "legendFormat": "Idle Bytes"
    },
    {
     "expr": "cells_process_runtime_go_mem_heap_sys_bytes{pod=\"$pod_id\"}",
     "legendFormat": "Heap Bytes"
    }
   ]
  },
  {
   "title": "Cells All Processes RAM",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 10, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(cells_process_runtime_go_mem_heap_alloc_bytes{service=\"cells\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$ns\", image!=\"\"}[$__rate_interval])) by (pod)",
       "legendFormat": "CPU Load average"
      }
     ]
    },
    {
     "title": "# Go Routines",
     "type": "timeseries",
     "description": "Might be an indicator of CPU processing",
     "gridPos": { "h": 8, "w": 10, "x": 12, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(cells_process_runtime_go_goroutines{job=\"cells\",instance=~\".*\"}) by (instance)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP(S) req. avg. duration by end point",
     "type": "timeseries",
     "description": "we sum by route to avoid polluting the legend between reboot",
     "gridPos": { "h": 12, "w": 10, "x": 0, "y": 325 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(cells_http_server_duration_milliseconds_sum{job=\"cells\",http_route=~\".*\"}[5m])) by (http_route)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Nb of requests per sec. per endpoint",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 7, "x": 10, "y": 325 },
     "targets": [
      {
       "expr": "sum(rate(cells_http_server_duration_milliseconds_count{job=\"cells\",http_route=~\".*\"}[5m])) by (http_route)",
       "legendFormat": "{{http_route}}"
      }
     ]
    },
    {
     "title": "Nb of requests per sec. (Total) ",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 5, "x": 17, "y": 325 },
     "targets": [
      {
       "expr": "sum(rate(cells_http_server_duration_milliseconds_count{job=\"cells\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "API Response Times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rest API calls: Response Time (avg. on 5m frames)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 326 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "avg_over_time(cells_rest_time_nanoseconds{pod=\"$pod_id\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rest Calls per second",
     "type": "timeseries",
     "description": "OpenTelemetry Int64Counter instruments are monotonic, meaning they only go up, and they represent a cumulative total either since:\n- The start of your process\n- The last exporter reset (if applicable).\nThey are not rate-based by default — there is no built-in time unit associated with the values.\n\n==> we add a rate in grafana to compute the nb of call per duration",
     "gridPos": { "h": 10, "w": 11, "x": 11, "y": 326 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(cells_rest_calls{job=\"cells\"}[5m]))",
       "legendFormat": "Aggregated Total"
      }
     ]
    },
    {
     "title": "GRPC calls: Response Time (avg. on 5m frames)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 336 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "rate(cells_grpc_time_sum{job=\"cells\"}[5m]) / rate(cells_grpc_time_count{job=\"cells\"}[5m])",
       "legendFormat": "{{service}}"
      },
      {
       "expr": "avg_over_time(cells_grpc_time_nanoseconds{job=\"cells\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "All GRPC Calls per second",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 8, "y": 336 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(cells_grpc_calls{pod=\"$pod_id\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GRPC Calls per second",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 15, "y": 336 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(cells_grpc_calls{pod=\"$pod_id\"}[5m])",
       "legendFormat": "{{service}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cells Open Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "DB Open Connections",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 384 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "cells_go_sql_connections_open", "legendFormat": "Open Connections" },
      { "expr": "cells_go_sql_connections_idle", "legendFormat": "Idle Connections" }
     ]
    },
    {
     "title": "Scheduler - Concurrent Active Workers",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 11, "y": 384 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(cells_activeWorkers{pod=\"$pod_id\"})"
      }
     ]
    },
    {
     "title": "Selected Process Streams",
     "type": "timeseries",
     "description": "Cumulates all open gRPC streams on all processes",
     "gridPos": { "h": 15, "w": 22, "x": 0, "y": 394 },
     "targets": [
      {
       "expr": "cells_open_streams{namespace=\"$ns\", pod=\"$pod_id\"}",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  }
 ]
}