{
 "title": "Wire Compute",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(http_request_duration_seconds_count,namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(http_request_duration_seconds_count,service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pod_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"${service}-.*\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"${service}-.*\", resource=\"memory\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"${service}-.*\", resource=\"memory\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "OOMKills",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_last_terminated_reason{namespace=\"$namespace\", pod=~\"${service}-.*\", reason=\"OOMKilled\"})",
     "legendFormat": "{{pod}} - {{reason}}"
    }
   ]
  },
  {
   "title": "Haskell Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gc_bytes_used_current{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gc_seconds_cpu{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(pod_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"${service}-.*\"})[$__rate_interval]",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"${service}-.*\", resource=\"cpu\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"${service}-.*\", resource=\"cpu\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "CPU Throttles ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(container_cpu_cfs_throttled_seconds_total{namespace=\"$namespace\", pod=~\"${service}-.*\"})[$__rate_interval]",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Open Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "net_connections{namespace=\"$namespace\", service=\"${service}\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(net_errors{namespace=\"$namespace\", service=\"${service}\"})[$__rate_interval]",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Bandwidth Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"${service}-.*\"})[$__rate_interval]",
     "legendFormat": "Rx - {{pod}}"
    },
    {
     "expr": "- irate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"${service}-.*\"})[$__rate_interval]",
     "legendFormat": "Tx - {{pod}}"
    }
   ]
  }
 ]
}