{
 "title": "Nginz logs",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "loki" },
   {
    "name": "namespace",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Nginz logs 5xx",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\", app=\"nginz\", container=\"nginz\"} | pattern `<remote_addr> <_> \"<timestamp>\" \"<method> <path> <_> <status> <bytes_sent> \"<_>\" \"<user_agent>\" <_> <_> <request_time> <_> - <user> <conn> <request_id> <_> \"<_>\"` | status =~ \"5..\""
    }
   ]
  },
  {
   "title": "Nginz logs 5xx rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate({namespace=~\"$namespace\", app=\"nginz\", container=\"nginz\"} | pattern `<remote_addr> <_> \"<_>\" \"<method> <path> <_> <status> <bytes_sent> \"<_>\" \"<user_agent>\" <_> <_> <request_time> <_> - <user> <conn> <request_id> <_> \"<_>\"` | status =~ \"5..\"[$__interval]))"
    }
   ]
  },
  {
   "title": "Nginz logs ALL requests rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate({namespace=~\"$namespace\", app=\"nginz\", container=\"nginz\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Nginz logs: slow queries > 0.5 seconds",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\", app=\"nginz\", container=\"nginz\"} | pattern `<remote_addr> <_> \"<_>\" \"<method> <path> <_> <status> <bytes_sent> \"<_>\" \"<user_agent>\" <_> <_> <request_time> <_> - <user> <conn> <request_id> <_> \"<_>\"` | request_time > 0.5 | path !~ \"/await.*\""
    }
   ]
  },
  {
   "title": "Nginz ALL logs",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\", app=\"nginz\", container=\"nginz\"} | pattern `<remote_addr> <_> \"<timestamp>\" \"<method> <path> <_> <status> <bytes_sent> \"<_>\" \"<user_agent>\" <_> <_> <request_time> <_> - <user> <conn> <request_id> <_> \"<_>\"`"
    }
   ]
  }
 ]
}