{
 "title": "SFT",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "datasource_logs", "query": "loki" },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "Logs (sft-server)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container=\"sftd\"}"
    }
   ]
  },
  {
   "title": "SFT Build Info",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (version)(sft_build_info{})"
    }
   ]
  },
  {
   "title": "SFT Calls",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sft_calls{}", "legendFormat": "{{ pod }}" },
    { "expr": "sum(sft_calls{})", "legendFormat": "total" }
   ]
  },
  {
   "title": "SFT Participants",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sft_participants{}", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(node) (\n  label_replace(\n    node_memory_MemTotal_bytes{} - node_memory_MemFree_bytes{} - node_memory_Buffers_bytes{} - node_memory_Cached_bytes{} - node_memory_Slab_bytes{},\n    \"node\", \"$1\", \"instance\", \"(.*)\"\n  )\n)\n* on(node) group_right\nkube_pod_info{namespace=\"$namespace\", created_by_name=\"sftd\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage (individual cores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-(label_replace(irate(node_cpu_seconds_total{mode=\"idle\"}[5m]), \"node\", \"$1\", \"instance\", \"(.*)\") * on(node) group_left kube_pod_info{namespace=\"$namespace\", created_by_name=\"sftd\"})",
     "legendFormat": "{{instance}} - cpu {{cpu}}"
    }
   ]
  },
  {
   "title": "Netstat",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(node) (\n  label_replace(\n    node_netstat_Tcp_CurrEstab{},\n    \"node\", \"$1\", \"instance\", \"(.*)\"\n  )\n)\n* on(node) group_right\nkube_pod_info{namespace=\"$namespace\", created_by_name=\"sftd\"}\n\n",
     "legendFormat": "TCP ActiveOpens dt ({{node}} {{pod}})"
    },
    {
     "expr": "sum by(node) (\n  label_replace(\n    node_netstat_Tcp_CurrEstab{},\n    \"node\", \"$1\", \"instance\", \"(.*)\"\n  )\n)\n* on(node) group_right\nkube_pod_info{namespace=\"$namespace\", created_by_name=\"sftd\"}\n",
     "legendFormat": "TCP CurrEstab ({{node}} {{pod}})"
    }
   ]
  },
  {
   "title": "Sockstat",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(node) (\n  label_replace(\n    node_sockstat_UDP_inuse{},\n    \"node\", \"$1\", \"instance\", \"(.*)\"\n  )\n)\n* on(node) group_right\n  kube_pod_info{namespace=\"$namespace\", created_by_name=\"sftd\"}\n",
     "legendFormat": "UDP inuse ({{ node }} {{ pod }})"
    },
    {
     "expr": "sum by(node) (\n  label_replace(\n    node_sockstat_TCP_inuse{},\n    \"node\", \"$1\", \"instance\", \"(.*)\"\n  )\n)\n* on(node) group_right\n  kube_pod_info{namespace=\"$namespace\", created_by_name=\"sftd\"}\n",
     "legendFormat": "TCP inuse ({{ node }} {{ pod }})"
    },
    {
     "expr": "sum by(node) (\n  label_replace(\n    node_sockstat_sockets_used{},\n    \"node\", \"$1\", \"instance\", \"(.*)\"\n  )\n)\n* on(node) group_right\n  kube_pod_info{namespace=\"$namespace\", created_by_name=\"sftd\"}\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}