{
 "title": "Wire Speed",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(http_request_duration_seconds_count,namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(http_request_duration_seconds_count,service)"
    }
   },
   {
    "name": "method",
    "query": {
     "query": "label_values(http_request_duration_seconds_count,method)"
    }
   },
   {
    "name": "handler",
    "query": {
     "query": "label_values(http_request_duration_seconds_count{service=\"$service\", method=\"$method\"},handler)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick Metrics (All Services)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "0.95p Response Time",
   "type": "stat",
   "description": "Non internal requests only",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", handler=~\"^/[^i].*\"}[$__rate_interval])) by (le))",
     "legendFormat": "0.95p"
    }
   ]
  },
  {
   "title": "0.99p Response Time",
   "type": "stat",
   "description": "Non internal requests only",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", handler=~\"^/[^i].*\"}[$__rate_interval])) by (le))",
     "legendFormat": "0.95p"
    }
   ]
  },
  {
   "title": "0.999p Response Time",
   "type": "stat",
   "description": "Non internal requests only",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", handler=~\"^/[^i].*\"}[$__rate_interval])) by (le))",
     "legendFormat": "0.95p"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "stat",
   "description": "Non internal requests only",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(http_request_duration_seconds_sum{namespace=\"$namespace\", handler=~\"^/[^i].*\"}[$__rate_interval]))/sum(irate(http_request_duration_seconds_count{namespace=\"$namespace\", handler=~\"^/[^i].*\"}[$__rate_interval]))",
     "legendFormat": "0.95p"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "stat",
   "description": "Except websockets",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(net_connections{service!=\"cannon\"})",
     "legendFormat": "0.95p"
    }
   ]
  },
  {
   "title": "Open Websockets",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(net_connections{service=\"cannon\"})",
     "legendFormat": "0.95p"
    }
   ]
  },
  {
   "title": "Overall Response Times and Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response Times from Nginx Ingress Controller",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_response_duration_seconds_bucket{ingress=\"nginx-ingress\"}[$__rate_interval])) by (le))",
       "legendFormat": "0.95p"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_response_duration_seconds_bucket{ingress=\"nginx-ingress\"}[$__rate_interval])) by (le))",
       "legendFormat": "0.99p"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(nginx_ingress_controller_response_duration_seconds_bucket{ingress=\"nginx-ingress\"}[$__rate_interval])) by (le))",
       "legendFormat": "0.999p"
      }
     ]
    },
    {
     "title": "Request Rate for Nginx Ingress Controller",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(irate(nginx_ingress_controller_request_duration_seconds_count{ingress=\"nginx-ingress\"}[$__rate_interval]))",
       "legendFormat": "Request Rate"
      }
     ]
    },
    {
     "title": "Response Times from Haskell Services (External endpoints only)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{handler=~\"^.[^i].*\", namespace=\"$namespace\"}[$__rate_interval])) by (le))",
       "legendFormat": "0.95p"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{handler=~\"^.[^i].*\", namespace=\"$namespace\"}[$__rate_interval])) by (le))",
       "legendFormat": "0.99p"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(http_request_duration_seconds_bucket{handler=~\"^.[^i].*\", namespace=\"$namespace\"}[$__rate_interval])) by (le))",
       "legendFormat": "0.999p"
      }
     ]
    },
    {
     "title": "Request Rate for Haskell Services (External endpoints only)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(irate(http_request_duration_seconds_count{namespace=\"$namespace\", handler=~\"/[^i].*\"}[$__rate_interval]))",
       "legendFormat": "Request Rate"
      }
     ]
    },
    {
     "title": "Response Times from Haskell Services (Internal endpoints only)",
     "type": "timeseries",
     "description": "Except /i/status",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{handler=~\"^/i/.*\", handler!=\"/i/status\", namespace=\"$namespace\"}[$__rate_interval])) by (le))",
       "legendFormat": "0.95p"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{handler=~\"^/i/.*\", handler!=\"/i/status\", namespace=\"$namespace\"}[$__rate_interval])) by (le))",
       "legendFormat": "0.99p"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(http_request_duration_seconds_bucket{handler=~\"^/i/.*\", handler!=\"/i/status\", namespace=\"$namespace\"}[$__rate_interval])) by (le))",
       "legendFormat": "0.999p"
      }
     ]
    },
    {
     "title": "Request Rate in Haskell Services (Internal endpoints only)",
     "type": "timeseries",
     "description": "Except /i/status",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(irate(http_request_duration_seconds_count{namespace=\"$namespace\", handler=~\"/i/.*\", handler!=\"/i/status\"}[$__rate_interval]))",
       "legendFormat": "Request Rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Service Wise Request Times and Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response Times by Service (External endpoints)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{handler=~\"^.[^i].*\", namespace=\"$namespace\", service=\"$service\"}[$__rate_interval])) by (le))",
       "legendFormat": "0.95p"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{handler=~\"^.[^i].*\", namespace=\"$namespace\", service=\"$service\"}[$__rate_interval])) by (le))",
       "legendFormat": "0.99p"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(http_request_duration_seconds_bucket{handler=~\"^.[^i].*\", namespace=\"$namespace\", service=\"$service\"}[$__rate_interval])) by (le))",
       "legendFormat": "0.999p"
      }
     ]
    },
    {
     "title": "Request Rate by Service (External endpoints only)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(irate(http_request_duration_seconds_count{namespace=\"$namespace\", handler=~\"^.[^i].*\", service=\"$service\"}[$__rate_interval]))",
       "legendFormat": "Request Rate"
      }
     ]
    },
    {
     "title": "Response Times by Service (Internal endpoints only)",
     "type": "timeseries",
     "description": "Except /i/status",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{handler=~\"^/i/.*\", handler!=\"/i/status\", namespace=\"$namespace\", service=\"$service\"}[$__rate_interval])) by (le))",
       "legendFormat": "0.95p"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{handler=~\"^/i/.*\", handler!=\"/i/status\", namespace=\"$namespace\", service=\"$service\"}[$__rate_interval])) by (le))",
       "legendFormat": "0.99p"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(http_request_duration_seconds_bucket{handler=~\"^/i/.*\", handler!=\"/i/status\", namespace=\"$namespace\", service=\"$service\"}[$__rate_interval])) by (le))",
       "legendFormat": "0.999p"
      }
     ]
    },
    {
     "title": "Request Rate by Service (Internal endpoints only)",
     "type": "timeseries",
     "description": "Except /i/status",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(irate(http_request_duration_seconds_count{namespace=\"$namespace\", handler=~\"/i/.*\", handler!=\"/i/status\", service=\"$service\"}[$__rate_interval]))",
       "legendFormat": "Request Rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Handler Heatmaps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "0.999p Response Times",
     "type": "heatmap",
     "gridPos": { "h": 44, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sort(histogram_quantile(0.999, sum(rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", handler=~\"^/[^i].*\", service=\"$service\"}[$__rate_interval])) by (method, handler, le))) ",
       "legendFormat": "{{method}} {{handler}}"
      }
     ]
    },
    {
     "title": "Average Response Times",
     "type": "heatmap",
     "gridPos": { "h": 44, "w": 24, "x": 0, "y": 62 },
     "targets": [
      {
       "expr": "sort(sum(increase(http_request_duration_seconds_sum{namespace=\"$namespace\", handler=~\"^/[^i].*\", service=\"$service\"}[$__rate_interval])) by (method, handler) / sum(increase(http_request_duration_seconds_count{namespace=\"$namespace\", handler=~\"^/[^i].*\", service=\"$service\"}[$__rate_interval])) by (method, handler))",
       "legendFormat": "{{method}} {{handler}}"
      }
     ]
    }
   ]
  },
  { "title": "Handler Wise", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Response Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{method=\"$method\", service=\"$service\", handler=\"$handler\", namespace=\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "0.95p"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{method=\"$method\", service=\"$service\", handler=\"$handler\", namespace=\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "0.99p"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(http_request_duration_seconds_bucket{method=\"$method\", service=\"$service\", handler=\"$handler\", namespace=\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "0.999p"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(http_request_duration_seconds_count{namespace=\"$namespace\", service=\"$service\",  method=\"$method\", handler=\"$handler\",}[$__rate_interval]))",
     "legendFormat": "Request Rate"
    }
   ]
  }
 ]
}