{
 "title": "Message Stats - gundeck/cannon/galley/brig",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "Brig Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Registrations/invitations/code requests (brig)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{handler=\"/teams/:tid/invitations\", status_code=\"201\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "invitations/sec(201)"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{handler=\"/register\", status_code=\"201\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "registration/sec(201)"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{handler=\"/activate/send\", status_code=~\"200\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "code_requests/sec(200)"
    }
   ]
  },
  {
   "title": "Prekey Fetching Latencies (brig)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(le) (increase(http_request_duration_seconds_bucket{handler=\"/users/prekeys\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Number of prekeys requested every 5m (brig)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{handler=\"/users/prekeys\", status_code=~\"2..\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(increase(http_request_duration_seconds_count{handler=\"/users/prekeys\", status_code=~\"5..\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Dynamodb requests failed/throttled every 5m (brig)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(client_opt_lock_optimistic_lock_grab_attempt_failed[5m]))",
     "legendFormat": "attempts_failed"
    },
    {
     "expr": "sum(increase(client_opt_lock_optimistic_lock_failed[5m]))",
     "legendFormat": "optimistic_lock_failed"
    },
    {
     "expr": "sum(increase(client_opt_lock_provisioned_throughput_exceeded[5m]))",
     "legendFormat": "throughput_exceeded"
    }
   ]
  },
  {
   "title": "Network connections",
   "type": "timeseries",
   "description": "Also see the BrigHoardingConnections issue at https://wearezeta.atlassian.net/browse/BE-287",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(net_connections{namespace=\"$namespace\"}) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MLS Endpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by(service, handler) (increase(http_request_duration_seconds_count{handler=~\".*mls.*\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cannon Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connected Clients (cannon)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(net_websocket_clients{namespace=\"$namespace\"})",
     "legendFormat": "Connected Clients"
    }
   ]
  },
  {
   "title": "Cargohold",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Asset uploads as % by Status Code (cargohold)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{service=\"cargohold\", handler=\"/assets/v3\", status_code=~\"2..\", namespace=\"$namespace\"}[10m]))",
     "legendFormat": "2XX"
    },
    {
     "expr": "sum(increase(http_request_duration_seconds_count{service=\"cargohold\", handler=\"/assets/v3\", status_code=~\"4..\", namespace=\"$namespace\"}[10m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(increase(http_request_duration_seconds_count{service=\"cargohold\", handler=\"/assets/v3\", status_code=~\"5..\", namespace=\"$namespace\"}[10m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Asset uploads by Status Code (cargohold)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{service=\"cargohold\", handler=\"/assets/v3\", status_code=~\"4..\", namespace=\"$namespace\"}[10m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(increase(http_request_duration_seconds_count{service=\"cargohold\", handler=\"/assets/v3\", status_code=~\"5..\", namespace=\"$namespace\"}[10m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Gundeck Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Message Push Latencies (gundeck)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{handler=\"/i/push/v2\", namespace=\"$namespace\"}[5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Native Push (Outgoing) (gundeck)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(push_native_success{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Success"
    },
    {
     "expr": "-sum(increase(push_native_disabled{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "-Disabled"
    },
    {
     "expr": "-sum(increase(push_native_invalid{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "-Invalid"
    },
    {
     "expr": "-sum(increase(push_native_errors{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "-Errors"
    }
   ]
  },
  {
   "title": "Push Rate (incoming) (gundeck)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{service=\"gundeck\", handler=\"/i/push/v2\", namespace=\"$namespace\"}[5m])) by (status_code)",
     "legendFormat": "{{ status_code }}"
    }
   ]
  },
  {
   "title": "Push Rate (incoming) (gundeck)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{service=\"gundeck\", handler=\"/i/push/v2\", namespace=\"$namespace\"}[5m])) by (status_code)",
     "legendFormat": "{{ status_code }}"
    }
   ]
  },
  {
   "title": "Galley Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Message POSTing Latencies (galley)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{handler=\"/conversations/:cnv/otr/messages\", namespace=\"$namespace\"}[5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "OTR Message Receives as % by Status Code (galley)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{service=\"galley\", handler=\"/conversations/:cnv/otr/messages\", status_code=~\"2..\", namespace=\"$namespace\"}[10m]))",
     "legendFormat": "2XX"
    },
    {
     "expr": "sum(increase(http_request_duration_seconds_count{service=\"galley\", handler=\"/conversations/:cnv/otr/messages\", status_code=~\"400\", namespace=\"$namespace\"}[10m]))",
     "legendFormat": "400"
    },
    {
     "expr": "sum(increase(http_request_duration_seconds_count{service=\"galley\", handler=\"/conversations/:cnv/otr/messages\", status_code=~\"5..\", namespace=\"$namespace\"}[10m]))",
     "legendFormat": "5XX"
    },
    {
     "expr": "sum(increase(http_request_duration_seconds_count{service=\"galley\", handler=\"/conversations/:cnv/otr/messages\", status_code=~\"412\"}[10m]))",
     "legendFormat": "412"
    }
   ]
  },
  {
   "title": "Messages Sent every 5m (galley)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{handler=\"/conversations/:cnv/otr/messages\", status_code=~\"2..\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(http_request_duration_seconds_count{handler=\"/conversations/:cnv_domain/:cnv/proteus/messages\", status_code=~\"2..\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Calls to the broadcast endpoint every 15m (galley)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{handler=\"/broadcast/otr/messages\",status_code=~\"2..\", namespace=\"$namespace\"}[15m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(increase(http_request_duration_seconds_count{handler=\"/broadcast/otr/messages\",status_code=~\"4..\", namespace=\"$namespace\"}[15m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(increase(http_request_duration_seconds_count{handler=\"/broadcast/otr/messages\",status_code=~\"5..\", namespace=\"$namespace\"}[15m]))",
     "legendFormat": "5xx"
    }
   ]
  }
 ]
}