{
 "title": "Flake News Overview",
 "description": "Overview of flake-news runs",
 "tags": [ "flake-news" ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "db", "query": "postgres" },
   {
    "name": "run_id",
    "query": "Select run_id from test_suite_runs order by run_id desc\n "
   }
  ]
 },
 "panels": [
  {
   "title": "Test suite failures in the selected run",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT suite, failed_runs, time FROM test_suite_runs \nWHERE run_id = '$run_id'\nAND failed_runs > 0;"
    }
   ]
  },
  {
   "title": "Test suite failures in the selected run",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT suite, failed_runs, failed_runs + successful_runs as total_runs FROM test_suite_runs \nWHERE run_id = '$run_id' "
    }
   ]
  },
  {
   "title": "Overall Flake Probability",
   "type": "gauge",
   "description": "Assuming test suites flake independently.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT 1 - exp(sum(ln(successful_runs/100.0))) as failure_rate FROM test_suite_runs \nWHERE run_id = '$run_id'"
    }
   ]
  },
  {
   "title": "History of overall flake probability",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT 1 - exp(sum(ln(successful_runs/100.0))) as \"flake probability\", time FROM test_suite_runs\nWHERE successful_runs != 0\nGROUP BY time;"
    }
   ]
  },
  {
   "title": "Test cases that failed in the selected run",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT name, failure_count, ts.version, ts.run_id, ts.suite\nfrom test_case_runs, test_suite_runs as ts \nwhere test_case_runs.test_suite_run_id = ts.id\n  and ts.run_id = '$run_id'\n  and failure_count != 0 \norder by failure_count desc;"
    }
   ]
  },
  {
   "title": "Overall Test Suite Failures",
   "type": "timeseries",
   "description": "No of times a test suite failed during a run of flake-news.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT suite, failed_runs, time FROM test_suite_runs ORDER BY time"
    }
   ]
  },
  {
   "title": "Test Case Failures",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT name, failure_count, ts.time from test_case_runs, test_suite_runs as ts where test_case_runs.test_suite_run_id = ts.id and failure_count != 0 ORDER BY ts.time "
    }
   ]
  },
  {
   "title": "Overall Test Suite Runs",
   "type": "timeseries",
   "description": "No of times a test suite finished during a run of flake-news.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT suite, failed_runs + successful_runs as total_runs, time FROM test_suite_runs ORDER BY time"
    }
   ]
  }
 ]
}