{
 "title": "Logs / Metrics data usage, per tenant",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "VM Datapoint ingestion rate per s, per tenant",
   "type": "timeseries",
   "description": "This queries the number of inserted data rows in VM. Number is divided by 2 (as we duplicate the data written inside the cluster to two vmstorage pods)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dps" } },
   "targets": [
    {
     "expr": "increase(sum by (accountID) (vm_tenant_inserted_rows_total{})[1m])/60 / 2",
     "legendFormat": "{{accountID}}"
    }
   ]
  },
  {
   "title": "Loki Ingester, chunk stored rate received by tenant",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "increase(loki_ingester_chunk_stored_bytes_total{}[1m])/60 *8",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Tempo Ingester Rate received",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "increase(tempo_ingester_bytes_received_total{}[1m])/60 * 8",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Ingress POST Data Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "increase(sum by (path, method) (nginx_ingress_controller_request_size_sum{host=\"monitoring.zinfra.io\",ingress=\"vmauth-main\"})[1m])/60*8",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  }
 ]
}