{
 "title": "Wire Services",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "service",
    "query": "brig,galley,cannon,gundeck,cargohold,spar,federator"
   },
   { "name": "datasource", "query": "prometheus" },
   { "name": "datasource_logs", "query": "loki" },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "README",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<strong>Haskell Service Statistics</strong><br />\n<small>Change the $(service) variable to see stats for each service\n<p>This does not apply to the Global Metrics section.\n</small>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Global Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "5XXs By Service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status_code=~\"5..\", namespace=\"$namespace\"}[5m])) by (service)",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "5XX/s per handler (current time range) - all services",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status_code=~\"5..\", namespace=\"$namespace\"}[$__range])) by (service, method, handler)",
     "legendFormat": "# 5XXs"
    }
   ]
  },
  {
   "title": "Error logs - all services in $namespace",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\"} | json | level = \"Error\""
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum by(service) (increase(kube_deployment_metadata_generation{namespace=~\"$namespace\", deployment=\"$service\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$service request stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Request Breakdown - $service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status_code=~\"2..\", service=\"$service\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "2XX"
    },
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status_code=~\"4..\", service=\"$service\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status_code=~\"5..\", service=\"$service\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Network Connections per pod (stacked) - $service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "net_connections{service=\"$service\", namespace=\"$namespace\"}",
     "legendFormat": "{{ pod }}",
     "target": "alias(scale(scaleToSeconds(nonNegativeDerivative(sumSeries(gundeck.*.eu-west-1.compute.internal.interface.eth0.if_octets.rx)), 1), 0.001), 'kb/s - inbound')"
    }
   ]
  },
  {
   "title": "Request rate by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{service=\"$service\", handler!=\"/i/status\", namespace=\"$namespace\"}[1m])) by (method, handler)",
     "legendFormat": "{{ method }} {{ handler }}"
    }
   ]
  },
  {
   "title": "4XX/s per handler (current time range) - $service",
   "type": "table",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status_code=~\"4..\", service=\"$service\", namespace=\"$namespace\"}[$__range])) by (handler, status_code)",
     "legendFormat": "# 5XXs"
    }
   ]
  },
  {
   "title": "5XX/s per handler (current time range) - $service",
   "type": "table",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status_code=~\"5..\", service=\"$service\", namespace=\"$namespace\"}[$__range])) by (handler)",
     "legendFormat": "# 5XXs"
    }
   ]
  },
  {
   "title": "Latency by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "topk(5, avg(rate(http_request_duration_seconds_sum{service=\"$service\", handler!~\"/i/status|prometheus\", namespace=\"$namespace\"}[5m])) by (handler))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Traffic (+RX/-TX) - $service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"$service.*\"}[$__rate_interval])) by (pod)",
     "legendFormat": "RX {{pod}}"
    },
    {
     "expr": "- sum(irate(container_network_transmit_bytes_total{namespace=~\"$namespace\", pod=~\"$service.*\"}[$__rate_interval])) by (pod)",
     "legendFormat": "TX {{pod}}"
    }
   ]
  },
  {
   "title": "disk bytes / s (+r/-w)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_bytes_total{namespace=\"$namespace\",pod=~\"$service.*\"}[1m])) by (pod)",
     "legendFormat": "Read Bytes {{ pod }}"
    },
    {
     "expr": "-sum(irate(container_fs_writes_bytes_total{namespace=\"$namespace\",pod=~\"$service.*\"}[1m])) by (pod)",
     "legendFormat": "Write Bytes {{ pod }}"
    }
   ]
  },
  { "title": "$service logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 }, "repeat": "service" },
  {
   "title": "Error logs $service",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\", app=\"$service\"} | json | level = \"Error\""
    }
   ]
  },
  {
   "title": "Warning logs $service",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\", app=\"$service\"} | json | level = \"Warn\""
    }
   ]
  },
  {
   "title": "$service Resource Consumption",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$service.*\"}[$__rate_interval])) by (pod)",
     "legendFormat": "CPU usage ({{ pod }})"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$service.*\", resource=\"cpu\"}) by (pod)\n",
     "legendFormat": "requests ({{ pod }})"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"$service.*\", resource=\"cpu\"}) by (pod)\n",
     "legendFormat": "limits ({{ pod }})"
    }
   ]
  },
  {
   "title": "Memory Usage - $service (Log Scale)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\", pod=~\"$service.*\"}",
     "legendFormat": "Resource Limit ({{ pod }})",
     "target": "alias(scale(averageSeries(gundeck.*.eu-west-1.compute.internal.memory.memory.used), 0.000001), 'used')"
    },
    {
     "expr": "gc_bytes_used_current{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "Memory In Use  (Haskell) ({{ pod }})",
     "target": "alias(scale(averageSeries(gundeck.*.eu-west-1.compute.internal.memory.memory.used), 0.000001), 'used')"
    },
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\", pod=~\"$service.*\"}",
     "legendFormat": "Resource Requests ({{ pod }})",
     "target": "alias(scale(averageSeries(gundeck.*.eu-west-1.compute.internal.memory.memory.used), 0.000001), 'used')"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", pod=~\"$service.*\"}) by (pod)",
     "legendFormat": "Memory In Use (Process) ({{ pod }})",
     "target": "alias(scale(averageSeries(gundeck.*.eu-west-1.compute.internal.memory.memory.used), 0.000001), 'used')"
    }
   ]
  }
 ]
}