{
 "title": "Calling / TURN / coturn",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "datasource_logs", "query": "loki" },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "Top rate-limited IP addresses",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate({app=\"coturn\"} |= `rate limit exceeded` | pattern `<_>INFO: 401 rate limit exceeded from <ip>, response not sent` [$__interval])",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "TURN logs",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{app=\"coturn\", container=\"coturn\"} |= ``"
    }
   ]
  },
  { "title": "coturn", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Allocations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(turn_total_allocations{namespace=\"$namespace\", job=\"coturn\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "(sum by (pod) (turn_total_allocations{namespace=\"$namespace\", job=\"coturn\"})) * on (pod) group_right kube_pod_info",
     "legendFormat": "{{pod}} / {{node}}"
    }
   ]
  },
  {
   "title": "Pod network traffic",
   "type": "timeseries",
   "description": "Network traffic usage reported by coturn. Note that per-session traffic usage is only reported after sessions have ended.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "-(sum by(pod) (rate(turn_total_traffic_sentb{namespace=\"$namespace\", job=\"coturn\"}[2m])) * on (pod) group_right kube_pod_info)",
     "legendFormat": "{{pod}} / {{node}} (sent)"
    },
    {
     "expr": "(sum by(pod) (rate(turn_total_traffic_rcvb{namespace=\"$namespace\", job=\"coturn\"}[2m]))) * on(pod) group_right kube_pod_info",
     "legendFormat": "{{pod}} / {{node}} (received)"
    }
   ]
  },
  {
   "title": "Pod network traffic (cumulative)",
   "type": "timeseries",
   "description": "Network traffic usage reported by coturn. Note that per-session traffic usage is only reported after sessions have ended.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(turn_total_traffic_sentb{namespace=\"$namespace\", job=\"coturn\"}[2m])) * -1",
     "legendFormat": "Bytes sent"
    },
    {
     "expr": "sum(rate(turn_total_traffic_rcvb{namespace=\"$namespace\", job=\"coturn\"}[2m]))",
     "legendFormat": "Bytes received"
    }
   ]
  },
  {
   "title": "Pod open file descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "process_open_fds{namespace=\"$namespace\",job=\"coturn\"} * on (pod) group_right kube_pod_info",
     "legendFormat": "{{pod}} / {{node}}"
    },
    {
     "expr": "sum(process_open_fds{namespace=\"$namespace\", job=\"coturn\"})",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "coturn (host nodes)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "CPU total (coturn nodes)",
   "type": "timeseries",
   "description": "This panel only includes CPU usage for nodes which are running in the coturn namespace and which are exposed to Grafana in the coturn scrape job.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (mode) (\n  sum by (node) (\n    kube_pod_info{namespace=\"$namespace\", created_by_name=\"coturn\"}\n    * on (pod) group_left\n    up{namespace=\"$namespace\",job=\"coturn\"}\n  )\n  * on (node) group_right\n  label_replace(rate(node_cpu_seconds_total{instance=~\"worker-.*|shoot-.*|ip-.*\"}[2m]), \"node\", \"$1\", \"instance\", \"(.*)\")\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network (coturn nodes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (node) (kube_pod_info{namespace=\"$namespace\", created_by_name=\"coturn\"} * on (node) group_left label_replace(sum by (instance) (rate(node_network_transmit_bytes_total{device=~\"(eth0|ens[0-9]+)\"}[2m])), \"node\", \"$1\", \"instance\", \"(.*)\"))",
     "legendFormat": "{{node}} (receive)"
    },
    {
     "expr": "-sum by (node) (kube_pod_info{namespace=\"$namespace\", created_by_name=\"coturn\"} * on (node) group_left label_replace(sum by (instance) (rate(node_network_receive_bytes_total{device=~\"(eth0|ens[0-9]+)\"}[2m])), \"node\", \"$1\", \"instance\", \"(.*)\"))",
     "legendFormat": "{{node}} (transmit)"
    }
   ]
  },
  {
   "title": "Network (coturn nodes, cumulative)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (kube_pod_info{namespace=\"$namespace\", created_by_name=\"coturn\"} * on (node) group_left label_replace(sum by (instance) (rate(node_network_transmit_bytes_total{device=~\"(eth0|ens[0-9]+)\"}[2m])), \"node\", \"$1\", \"instance\", \"(.*)\"))",
     "legendFormat": "Total egress"
    },
    {
     "expr": "-sum (kube_pod_info{namespace=\"$namespace\", created_by_name=\"coturn\"} * on (node) group_left label_replace(sum by (instance) (rate(node_network_receive_bytes_total{device=~\"(eth0|ens[0-9]+)\"}[2m])), \"node\", \"$1\", \"instance\", \"(.*)\"))",
     "legendFormat": "Total ingress"
    }
   ]
  },
  {
   "title": "Load averages (coturn nodes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(kube_pod_info{namespace=\"$namespace\", created_by_name=\"coturn\"} * on (node) group_left label_replace(sum by (instance) (node_load15), \"node\", \"$1\", \"instance\", \"(.*)\"))",
     "legendFormat": "{{node}} {{pod}} / 15min avg"
    },
    {
     "expr": "(kube_pod_info{namespace=\"$namespace\", created_by_name=\"coturn\"} * on (node) group_left label_replace(sum by (instance) (node_load5), \"node\", \"$1\", \"instance\", \"(.*)\"))",
     "legendFormat": "{{node}} {{pod}} / 5min avg"
    }
   ]
  },
  {
   "title": "Available memory (coturn nodes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (\n  label_replace(sum by(instance) (node_memory_MemFree_bytes), \"node\", \"$1\", \"instance\", \"(.*)\")\n  /\n  label_replace(sum by(instance) (node_memory_MemTotal_bytes), \"node\", \"$1\", \"instance\", \"(.*)\")\n)\n* on(node)\ngroup_left(pod)\nmax by(node) (\n  kube_pod_info{namespace=\"$namespace\", created_by_name=\"coturn\"}\n)",
     "legendFormat": "{{node}} {{pod}}"
    }
   ]
  }
 ]
}