{
 "title": "CPU and Memory",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "By Node Group", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU by Node Groups",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"cpu\"}) by (node)"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\"}) by (node)"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{job=\"kubelet\"}[1m])) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (node)"
    },
    {
     "expr": "sum(kube_node_labels{label_eks_amazonaws_com_nodegroup!=\"\"}) by (node, label_eks_amazonaws_com_nodegroup)"
    }
   ]
  },
  {
   "title": "CPU Requets by Node Groups",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (node) * on (node) group_right sum(kube_node_labels{label_eks_amazonaws_com_nodegroup!=\"\"}) by (node, label_eks_amazonaws_com_nodegroup)) by (label_eks_amazonaws_com_nodegroup) / sum(sum(kube_node_status_allocatable{resource=\"cpu\"}) by (node) * on (node) group_right sum(kube_node_labels{label_eks_amazonaws_com_nodegroup!=\"\"}) by (node, label_eks_amazonaws_com_nodegroup)) by (label_eks_amazonaws_com_nodegroup)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage by Node Groups",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(sum(irate(container_cpu_usage_seconds_total{job=\"kubelet\"}[1m])) by (node) * on (node) group_right sum(kube_node_labels{label_eks_amazonaws_com_nodegroup!=\"\"}) by (node, label_eks_amazonaws_com_nodegroup)) by (label_eks_amazonaws_com_nodegroup) / sum(sum(kube_node_status_allocatable{resource=\"cpu\"}) by (node) * on (node) group_right sum(kube_node_labels{label_eks_amazonaws_com_nodegroup!=\"\"}) by (node, label_eks_amazonaws_com_nodegroup)) by (label_eks_amazonaws_com_nodegroup)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory by Node Group",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"memory\"}) by (node)"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\"}) by (node)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\"}) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests) by (node)"
    },
    {
     "expr": "sum(kube_node_labels{label_eks_amazonaws_com_nodegroup!=\"\"}) by (node, label_eks_amazonaws_com_nodegroup)"
    }
   ]
  },
  {
   "title": "Memory Requets by Node Groups",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(sum(kube_pod_container_resource_requests{resource=\"memory\"}) by (node) * on (node) group_right sum(kube_node_labels{label_eks_amazonaws_com_nodegroup!=\"\"}) by (node, label_eks_amazonaws_com_nodegroup)) by (label_eks_amazonaws_com_nodegroup) / sum(sum(kube_node_status_allocatable{resource=\"memory\"}) by (node) * on (node) group_right sum(kube_node_labels{label_eks_amazonaws_com_nodegroup!=\"\"}) by (node, label_eks_amazonaws_com_nodegroup)) by (label_eks_amazonaws_com_nodegroup)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage by Node Groups",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(sum(container_memory_working_set_bytes{job=\"kubelet\"}) by (node) * on (node) group_right sum(kube_node_labels{label_eks_amazonaws_com_nodegroup!=\"\"}) by (node, label_eks_amazonaws_com_nodegroup)) by (label_eks_amazonaws_com_nodegroup) / sum(sum(kube_node_status_allocatable{resource=\"memory\"}) by (node) * on (node) group_right sum(kube_node_labels{label_eks_amazonaws_com_nodegroup!=\"\"}) by (node, label_eks_amazonaws_com_nodegroup)) by (label_eks_amazonaws_com_nodegroup)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "By Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "CPU by Node",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"cpu\"}) by (node)"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\"}) by (node)"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{job=\"kubelet\"}[1m])) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (node)"
    },
    {
     "expr": "sum(kube_node_labels{label_eks_amazonaws_com_nodegroup!=\"\"}) by (node, label_eks_amazonaws_com_nodegroup)"
    }
   ]
  },
  {
   "title": "CPU Requets by Node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (node) / sum(kube_node_status_allocatable{resource=\"cpu\"}) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage by Node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{job=\"kubelet\"}[1m])) by (node) / sum(kube_node_status_allocatable{resource=\"cpu\"}) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory by Node",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"memory\"}) by (node)"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\"}) by (node)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\"}) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests) by (node)"
    },
    {
     "expr": "sum(kube_node_labels{label_eks_amazonaws_com_nodegroup!=\"\"}) by (node, label_eks_amazonaws_com_nodegroup)"
    }
   ]
  },
  {
   "title": "Memory Requets by Node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests) by (node) / sum(kube_node_status_allocatable{resource=\"memory\"}) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage by Node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\"}) by (node) / sum(kube_node_status_allocatable{resource=\"memory\"}) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "By Namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Requests and Usage by Namesapce",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"}) by (namespace)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (namespace)"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{job=\"kubelet\"})) by (namespace)"
    }
   ]
  },
  {
   "title": "CPU Usage by namespace ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{job=\"kubelet\"})) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage by namespace ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{job=\"cadvisor\", container!=\"\"}[$__rate_interval])) by (namespace, pod, container) /sum(increase(container_cpu_cfs_periods_total{job=\"cadvisor\", container!=\"\"}[$__rate_interval])) by (namespace, pod, container) > 0",
     "legendFormat": "{{namespace}}/{{pod}}/{{container}}"
    }
   ]
  }
 ]
}