# This chart is meant to be used in ephemeral deployments, such as demo environments.
# TODO: look deeper into requirements and make a solid, commented values example file
postgresql:
  primary:
    persistence:
      enabled: false
  volumePermissions:
    image:
      repository: bitnami/os-shell
      tag: 12-debian-12-r46
