- hosts: cassandra
  any_errors_fatal: true
  environment: "{{ proxy_env | default({}) }}"
  vars:
    cassandra_keyspaces:
      - brig
      - galley
      - gundeck
      - spar
    # cassandra 3.11 doesn't support java 11 yet, use openjdk-8.
    java_packages:
      - openjdk-8-jre-headless
  roles:

    - role: ansible-role-ntp
      tags:
        - ntp
      when: not offline

    - role: ansible-role-java
      tags:
        - java

    - role: ansible-cassandra
      tags:
        - cassandra

    - role: ansible-ntp-verify
      tags:
        - ntp
      when: not offline
  tasks:
    # these are optional debug tasks to see that the cluser has come up sucessfully
    - shell: nodetool status
      register: nodetool_status
      tags:
        - cassandra
        - debug
    - debug: var=nodetool_status.stdout_lines
      tags:
        - cassandra
        - debug
