# See defaults in https://github.com/helm/charts/tree/master/stable/fluent-bit
fluent-bit:
  backend:
    type: es
    es:
      host: elasticsearch-ephemeral
  parsers:
    json:
      - extraEntries: |-
         Decode_Field_As escaped_utf8 log do_next
         Decode_Field_As json log

