apiVersion: v1
kind: ConfigMap
metadata:
  name: galley
data:
  {{- with .Values.config }}
  galley.yaml: |
    logNetStrings: True # log using netstrings encoding:
                        # http://cr.yp.to/proto/netstrings.txt
    logLevel: {{ .logLevel }}

    galley:
      host: 0.0.0.0
      port: 8080

    cassandra:
      endpoint:
        host: {{ .cassandra.host }}
        port: 9042
      keyspace: galley

    brig:
      host: brig
      port: 8080

    gundeck:
      host: gundeck
      port: 8080

    {{- if (.journal) }}
    journal:
      queueName: {{ .journal.queue }}
      endpoint: {{ .journal.endpoint }}
    {{- end }}

    settings:
      httpPoolSize: 128
      intraListing: false
      maxTeamSize: {{ .settings.maxTeamSize }}
      maxConvSize: {{ .settings.maxConvSize }}
      conversationCodeURI: {{ .settings.conversationCodeURI | quote }}
  {{- end }}
