replicaCount: 1
#  image:
#    tag: some-tag (only override if you want a newer/different version than what is in the chart)
config:
  externalUrls:
    backendRest: nginz-https.example.com
    backendWebsocket: nginz-ssl.example.com
    backendDomain: example.com
    appHost: teams.example.com
# See full list of available environment variables: https://github.com/wireapp/wire-team-settings/blob/dev/server/config.ts
envVars:
  APP_NAME: "Team Settings"
  ENFORCE_HTTPS: "true"
  FEATURE_CHECK_CONSENT: "false"
  FEATURE_ENABLE_DEBUG: "false"
  FEATURE_ENABLE_NEW_TEAM: "true"
  # NOTE: Uncomment this for legalhold support in the Team-settings UI
  # FEATURE_ENABLE_LEGAL_HOLD: "true"
  URL_ACCOUNT_BASE: "https://account.example.com"
  URL_WEBAPP_BASE: "https://webapp.example.com"
  URL_WEBSITE_BASE: "https://www.example.com"
  WEBSITE_LABEL: "www.example.com"
  CSP_EXTRA_CONNECT_SRC: "https://*.example.com, wss://*.example.com"
  CSP_EXTRA_IMG_SRC: "https://*.example.com"
  CSP_EXTRA_SCRIPT_SRC: "https://*.example.com"
  CSP_EXTRA_DEFAULT_SRC: "https://*.example.com"
  CSP_EXTRA_FONT_SRC: "https://*.example.com"
  CSP_EXTRA_FRAME_SRC: "https://*.example.com"
  CSP_EXTRA_MANIFEST_SRC: "https://*.example.com"
  CSP_EXTRA_OBJECT_SRC: "https://*.example.com"
  CSP_EXTRA_MEDIA_SRC: "https://*.example.com"
  CSP_EXTRA_PREFETCH_SRC: "https://*.example.com"
  CSP_EXTRA_STYLE_SRC: "https://*.example.com"
  CSP_EXTRA_WORKER_SRC: "https://*.example.com"
  IS_SELF_HOSTED: "true"
