fullnameOverride: demo-smtp
replicaCount: 1
image:
  repository: namshi/smtp
  tag: latest

service:
  port: 25

resources:
  limits:
   cpu: 500m
   memory: 500Mi
  requests:
   cpu: 100m
   memory: 128Mi

# Some relevant config options, check
# https://hub.docker.com/r/namshi/smtp/
# for more details
#
# config:
#   relayNetworks:
#
